---

- name: Install unattended-upgrades
  apt: name=unattended-upgrades state=installed
  tags: unattended-upgrades

- name: Deploy unattended-upgrades files for raspbian
  template: src=20auto-upgrades.j2 dest=/etc/apt/apt.conf.d/20auto-upgrades owner=root group=root mode=644
  tags: unattended-upgrades

- name: Deploy unattended-upgrades files for raspbian
  template: src=50unattended-upgrades-raspbian-{{ ansible_distribution_release }}.j2 dest=/etc/apt/apt.conf.d/50unattended-upgrades owner=root group=root mode=644
  when: raspbian_id.stat.exists == true and (ansible_distribution_release == 'wheezy' or ansible_distribution_release == 'jessie')
  tags: unattended-upgrades

- name: Deploy unattended-upgrades files for stock debian
  template: src=50unattended-upgrades-debian-{{ ansible_distribution_release }}.j2 dest=/etc/apt/apt.conf.d/50unattended-upgrades owner=root group=root mode=644
  when: raspbian_id.stat.exists == false and (ansible_distribution_release == 'wheezy' or ansible_distribution_release == 'jessie')
  tags: unattended-upgrades
