---

- name: Deploy random mac script on non-virtualized systems
  template: src=random-mac.j2 dest=/etc/network/if-pre-up.d/random-mac owner=root group=root mode=750
  when: ansible_virtualization_role == 'host' or ansible_virtualization_role == 'NA'
  tags: random-mac
