---

- name: Deploy random mac script on non-virtualized systems
  template: src=random-mac.sh.j2 dest=/etc/network/random-mac.sh owner=root group=root mode=750
  when: ansible_virtualization_role == 'host' or ansible_virtualization_role == 'NA'
  tags: random-mac

- name: Deploy random mac boot script
  template: src=pre-up-random-mac.j2 dest=/etc/network/if-pre-up.d/pre-up-random-mac owner=root group=root mode=750
  when: ansible_virtualization_role == 'host' or ansible_virtualization_role == 'NA'
  tags: random-mac
